apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo-db:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: mongodb
          containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: MONGODB_INITDB_DATABASE
          value: "nightscout"
        volumeMounts:
        - name: secretvolume
          readOnly: true
          mountPath: "/etc/secret-volume"
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: secretvolume
        secret:
          secretName: mongo-secret
      - name: mongo-data
        hostPath:
            path: /mongo-data
            type: DirectoryOrCreate