apiVersion: v1
kind: Service
metadata:
  name: mongodb-external-svc
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30100
  selector:
    app: mongodb
  type: NodePort
