apiVersion: v1
kind: Service
metadata:
  name: nighscout-cgm-svc
  labels:
    app: nightscout-cgm
spec:
  ports:
  - port: 1337
    protocol: TCP
    targetPort: 1337
    nodePort: 30101
  selector:
    app: nightscout-cgm
  type: NodePort