apiVersion: v1
kind: Service
metadata:
  labels:
    app: nightscout-reporter  
  name: ns-reporter-svc
spec:
  ports:
  - port: 80   
    protocol: TCP
    targetPort: 80
    nodePort: 30102
  selector:
    app: nightscout-reporter
  type: NodePort